Automated debian package building

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -33,6 +33,7 @@ branch=`git branch | grep \* | cut -d ' ' -f2`
 maintainer="Subutai Social"
 maintainer_email="jenkins@subut.ai"
 build_deb=1
+prefix=/usr
 
 while [ $# -ge 1 ]; do
     case "$1" in
@@ -49,7 +50,9 @@ while [ $# -ge 1 ]; do
             exit 0
             ;;
         --build=*) ;;
-        --prefix=*) ;;
+        --prefix=*) 
+            prefix=`echo ${1} | awk '{print substr($0,10)}'`
+            ;;
         --includedir=*) ;;
         --mandir=*) ;;
         --infodir=*) ;;
@@ -168,6 +171,7 @@ else
     echo "Build-Depends: debhelper (>=9)" >> debian/control
     echo "Standards-Version: 3.9.6" >> debian/control
     echo "Homepage: https://subut.ai" >> debian/control
+    echo "" >> debian/control
     echo "Package: subutai-$name_base" >> debian/control
     echo "Architecture: any" >> debian/control
     echo "Depends: \${shlibs:Depends}, \${misc:Depends}" >> debian/control
@@ -183,12 +187,19 @@ else
     fi
 fi
 
+echo "Downloading necessary packages"
+go get
+if [ $? != 0 ]; then
+    echo "Failed to get required packages. go get exited with error code $?"
+fi
+
 # generating config.make file
 echo "# config.make generated by configure script" > config.make
 echo "UPX_GO = $upx_go" >> config.make
 echo "NAME_BASE = $name_base" >> config.make
 echo "NAME_PREFIX = $name_prefix" >> config.make
 echo "BUILD_DEB = $build_deb" >> config.make
+echo "PREFIX = $prefix" >> config.make
 if [ "$upx_bin" != "" ]; then
     echo "UPX_BIN = $upx_bin" >> config.make
 fi
@@ -196,6 +207,7 @@ echo "export UPX_GO" >> config.make
 echo "export NAME_BASE" >> config.make
 echo "export BUILD_DEB" >> config.make
 echo "export NAME_PREFIX" >> config.make
+echo "export PREFIX" >> config.make
 if [ "$upx_bin" != "" ]; then
     echo "export UPX_BIN" >> config.make
 fi
