New building rules, mofied configure and makefile

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9,7 +9,16 @@ Configure p2p
 
 Options:
     --scheme=<build_scheme>
-    Builds p2p with specified build scheme. Supported schemes is: master, dev, branch. Default: master
+        Builds p2p with specified build scheme. Supported schemes is: master, dev, branch. Default: master
+
+    --no-debian
+        Disables build of deb file
+
+    --maintainer=<name>
+        Name of package maintainer
+
+    --maintainer-email=<email>
+        Email of package maintainer email. Appropriate GPG key should exist in the system
 
     --help
     Display this help screen
@@ -21,16 +30,38 @@ upx_go=$GOPATH/bin/goupx
 name_prefix=p2p
 scheme="master"
 branch=`git branch | grep \* | cut -d ' ' -f2`
+maintainer="Subutai Social"
+maintainer_email="jenkins@subut.ai"
+build_deb=1
 
 while [ $# -ge 1 ]; do
     case "$1" in
         --scheme=*)
             scheme="`echo ${1} | awk '{print substr($0,10)}'`" ;;
+        --maintainer=*)
+            maintainer="`echo ${1} | awk '{print substr($0,14)}'`" ;;
+        --maintainer-email=*)
+            maintainer_email="`echo ${1} | awk '{print substr($0,20)}'`" ;;
+        --no-debian)
+            build_deb=0 ;;
         --help)
             showhelp
             exit 0
             ;;
+        --build=*) ;;
+        --prefix=*) ;;
+        --includedir=*) ;;
+        --mandir=*) ;;
+        --infodir=*) ;;
+        --sysconfdir=*) ;;
+        --localstatedir=*) ;;
+        --disable-silent-rules) ;;
+        --libdir=*) ;;
+        --libexecdir=*) ;;
+        --disable-maintainer-mode) exit 0 ;;
+        --disable-dependency-tracking) ;;
         *)
+            echo "ERROR: Unknown argument: $1"
             showhelp
             exit 1
             ;;
@@ -78,9 +109,27 @@ echo "checking debuild"
 which debuild
 if [ $? != 0 ]; then
     echo "debuild was not found"
+elif [ $build_deb == 0 ]; then
+    echo "skipping deb package"
 else
-    # Prepare changelog: TODO
-    # date -d'11/25/2016' "+%a, %d %b %Y %H:%M:%S %z"
+    if [ "$maintainer" == "" ]; then
+        echo "Maintainer name should not be empty"
+        showhelp
+        exit 1
+    fi
+    echo "Checking GPG"
+    gpg_bin=`which gpg`
+    if [ $? != 0 ]; then
+        echo "GPG is not installed on this computer. Aborting"
+        exit 2
+    fi
+    echo "Checking GPG key"
+    key=`gpg --list-keys "$maintainer_email"`
+    if [ $? != 0 ]; then
+        echo "Failed to find GPG key for $maintainer_email"
+        exit 2
+    fi
+    # Preparing changelog
     rm -f deb-changelog.tmp
     started=0
     while IFS='' read -r line || [[ -n "$line" ]]; do
@@ -89,7 +138,7 @@ else
             if [ $started -eq 1 ]; then
                 date_formatted=`date -d"$release_date" "+%a, %d %b %Y %H:%M:%S %z"`
                 echo "" >> deb-changelog.tmp
-                echo " -- Subutai Social <jenkins@subut.ai> $date_formatted" >> deb-changelog.tmp
+                echo " -- $maintainer <$maintainer_email>  $date_formatted" >> deb-changelog.tmp
                 echo "" >> deb-changelog.tmp
                 started=0
             fi
@@ -99,13 +148,13 @@ else
             echo "subutai-$name_base ($version_num) unstable; urgency=medium" >> deb-changelog.tmp
             echo "" >> deb-changelog.tmp
         elif [ "$st" == "* " ]; then
-            echo " $line" >> deb-changelog.tmp
+            echo "  $line" >> deb-changelog.tmp
         fi
     done < CHANGELOG
     if [ $started -eq 1 ]; then
         date_formatted=`date -d"$release_date" "+%a, %d %b %Y %H:%M:%S %z"`
         echo "" >> deb-changelog.tmp
-        echo " -- Subutai Social <admin@subut.ai> $date_formatted" >> deb-changelog.tmp
+        echo " -- $maintainer <$maintainer_email>  $date_formatted" >> deb-changelog.tmp
         echo "" >> deb-changelog.tmp
         started=0
     fi
@@ -124,13 +173,17 @@ fi
 echo "# config.make generated by configure script" > config.make
 if [ "$upx_go" != "" ]; then
     echo "UPX_GO = $upx_go" >> config.make
-    echo "export UPX_GO" >> config.make
     echo "NAME_BASE = $name_base" >> config.make
-    echo "export NAME_BASE" >> config.make
     echo "NAME_PREFIX = $name_prefix" >> config.make
-    echo "export NAME_PREFIX" >> config.make
+    echo "BUILD_DEB = $build_deb" >> config.make
     if [ "$upx_bin" != "" ]; then
         echo "UPX_BIN = $upx_bin" >> config.make
+    fi
+    echo "export UPX_GO" >> config.make
+    echo "export NAME_BASE" >> config.make
+    echo "export BUILD_DEB" >> config.make
+    echo "export NAME_PREFIX" >> config.make
+    if [ "$upx_bin" != "" ]; then
         echo "export UPX_BIN" >> config.make
     fi
 fi
